### ISSUE TITLE
CRITICAL (CREATE NEW AD): As a user, I want to be able to create a new AD for a property. After successful creation, the ad is immediately displayed on the overview page

### ISSUE THREAD

**Issue by Slava-Berasneu** [sopra-fs22-group-15/cozycave-server#6]
- [x] sopra-fs22-group-15/cozycave-client#34
- [x] sopra-fs22-group-15/cozycave-client#26
- [X] https://github.com/sopra-fs22-group-15/cozycave-server/issues/89

**Comment by matthias-imhof** [comment]
https://github.com/sopra-fs22-group-15/cozycave-server/issues/89
