### ISSUE TITLE
MAJOR (SETTING ADDRESSES IN PROFILE): As a user, I want to be able to add, change and remove different addresses important to me in my profile

### ISSUE THREAD

**Issue by Slava-Berasneu** [sopra-fs22-group-15/cozycave-server#9]
- [x] sopra-fs22-group-15/cozycave-client#22
- [x] sopra-fs22-group-15/cozycave-client#52
- [x] https://github.com/sopra-fs22-group-15/cozycave-server/issues/90

**Comment by matthias-imhof** [comment]
- [ ] Possibility to set address
- [ ] Change address
- [ ] add multiple addresses at different locations
